# Generated by Django 5.2.13 on 2026-04-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Аренда/Бронь', 'verbose_name_plural': 'Аренда/Бронь'},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('reserved', 'Забронирована'), ('issued', 'На руках'), ('returned', 'Возвращена')], default='reserved', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок возврата'),
        ),
    ]
