# Generated by Django 5.2.13 on 2026-04-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_options_remove_loan_is_returned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Запись о выдаче', 'verbose_name_plural': 'Журнал выдачи'},
        ),
    ]
