# Generated by Django 5.2.13 on 2026-04-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год издания'),
        ),
    ]
